package com.source.interfaces.requisitions;
import java.util.List;
import java.util.Map;

public interface IPrCreate {
    void punchoutCreate();
    void adminLogin();
    void adminLogout();
    void requesterLoginPRCreate();
    void createButton();
    void purchaseType(String type, String purchaseType);
    void catalogTypeHandler(String type, String purchaseType);
    void title(String type, String purchaseType);
    void shipToYokogawa();
    void company();
    void businessUnit();
    void salesReferenceId(String purchaseType, String typ);
    List<String> project();
    void wbs(List<String> wbs);
    List<String> salesOrder(String purchaseType, int soNumber, String type);
    void serviceOrder(List<String> serviceOrder);
    void svoItemNumber();
    void departmentPic(String type);
    void purchaseGroup();
    void poType();
    void billableToCustomer();
    void caseMarking();
    void messageToSourcing();
    Map<String, String> vendor(String type, String purchaseType);
    void addItemsForBOP2BOP5(String type);
    List<String> rateContract(Map<String, String> rateContractArray);
    void incoterm();
    void shippingAddress();
    void shippingMode(String type, String purchaseType);
    void quotationRequiredBy();
    void expectedPOIssue(String type, String purchaseType);
    void expectedDelivery(String type, String purchaseType);
    void buyerManager();
    void projectManager();
    void checker(String type, String purchaseType);
    void rohsCompliance();
    void inspectionRequired(String type, String purchaseType);
    void oiAndTpCurrency();
    void orderIntake(String type);
    void targetPrice(String type, String purchaseType);
    void warrantyRequirements(String type);
    void priceValidity(String type);
    void liquidatedDamages();
    void tcasCompliance();
    void addLineRequisitionItemsCatalog(List<String> rateContract);
    void addLineRequisitionItemsNonCatalog();
    void editItemsForPunchout();
    void notes();
    void attachments();
    int prCreate(String type, String purchaseType);
}